# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChuckNorrisFacts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChuckNorrisFacts
    pod 'Alamofire', '~> 5.2'
    pod 'RxSwift', '6.0.0-rc.2'

  target 'ChuckNorrisFactsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChuckNorrisFactsUITests' do
    # Pods for testing
  end

end
